### ISSUE TITLE
Consider splitting to sub-packages

### ISSUE THREAD

**Issue by gmosx** [pointfreeco/swift-web#125]
I think this package is too monolithic. E.g. I just wanted to use the `Html` module and I got `BlueCryptor` as a dependency (and maybe more transient dependencies.

Did you consider creating multiple packages, i.e. swift-html, swift-css, etc.

**Comment by mbrandonw** [comment]
@gmosx Hey sorry for the late reply! So turns out that isn't necessary with SPM. A single repo can have multiple package.

For example, if you add `pointfreeco/swift-web` to your `Package.swift` but then only use, say, the `Html` package you will _only_ get the code for that library.

This allows us to have a monorepo but people can still pick and choose what they want to take. 

Does that clear things up?

**Comment by gmosx** [comment]
I think SPM downloads (and builds) the whole package, not only the sub-packages you use.

**Comment by mbrandonw** [comment]
It does download all the code, but this morning I tested a fresh project pulling in `pointfreeco/swift-web` but using only one of the dependencies, and the generated Xcode project included only the bare minimum of files needed. So it does not build anything that isn't explicitly used as a dependency.

We think it's an ok trade off to download the code as long as it doesn't build it.

**Comment by gmosx** [comment]
Well, I can live with that.

**Comment by mbrandonw** [comment]
Cool, thanks! And if you find any evidence to the contrary please do re-open. I'm pretty sure of my findings, but who knows what may change in SPM in the future!
